# name: Labeler

# on:
#   pull_request:

# permissions:
#   contents: read
#   pull-requests: write

# jobs:
#   label:
#     runs-on: ubuntu-latest
#     if: >-
#       ${{
#         (github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip ci]')) &&
#         (github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]'))
#       }}
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/labeler@v5
#         with:
#           configuration-path: .github/labeler.yml
